// src/public/scripts/vuetify/LoginDialog.vue
<template>
  <div>
    <v-dialog
      v-model="toprightdialog"
      max-width="450px"
    >
      <v-card>
        <v-progress-linear
          :active="loading"
          :indeterminate="loading"
          absolute
          top
          color="green"
        />
        <v-card-title>{{ l('layout.login.title') }}</v-card-title>
        <v-card-text>
          {{ l('layout.login.description') }}
          <v-container>
            <v-form
              ref="form"
              v-model="valid"
            >
              <v-text-field
                v-model="username"
                :rules="usernameRules"
                :label="l('layout.login.username')"
                :disabled="loading"
                color="green"
                required
              />
              <v-text-field
                v-model="password"
                :rules="passwordRules"
                type="password"
                :label="l('layout.login.password')"
                :disabled="loading"
                color="green"
                required
                @keyup.enter="login"
              />
            </v-form>
          </v-container>
        </v-card-text>
        <v-divider />
        <v-card-actions>
          <v-spacer />
          <v-btn
            color="inherit"
            text
            @click="toprightdialog = false"
          >
            {{ l('layout.login.close') }}
          </v-btn>
          <v-btn
            color="inherit"
            text
            @click="$refs.registerDialog.registerDialog = !$refs.registerDialog.registerDialog"
          >
            {{ l('layout.login.register') }}
          </v-btn>
          <v-btn
            color="green"
            text
            :disabled="loading"
            @click="login"
          >
            {{ l('layout.login.login') }}
          </v-btn>
        </v-card-actions>
      </v-card>
      <RegisterDialog ref="registerDialog" />
    </v-dialog>
    <v-snackbar
      v-model="snackbar"
      :timeout="3000"
    >
      {{ snackbarMessage }}
    </v-snackbar>
  </div>
</template>
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator';
import {getModule} from 'vuex-module-decorators';
import { Register } from '../register';
import Axios, { AxiosResponse } from 'axios';
import { b64 } from '../b64';
import { l } from '../locale';
import RegisterDialog from './RegisterDialog.vue';
import {encrypt} from '../encryption/AES';

@Component({
  components: {
    RegisterDialog
  }
})
export default class LoginDialog extends Vue {
  snackbarMessage = '';
  valid = false;
  validateUsername = Register.validateUsername
  validatePassword = Register.validatePassword
  usernameRules = [
    (v: string) => !!v || l('layout.login.usernameempty'),
    (v: string) => this.validateUsername(v) || l('layout.login.usernameinvalid')
  ]
  passwordRules = [
    (v: string) => !!v ||  l('layout.login.passwordempty'),
    (v: string) => this.validatePassword(v) || l('layout.login.passwordinvalid')
  ]
  username = '';
  password = '';
  toprightdialog = false;
  snackbar = false;
  loading = false;
  l = l;
  login() {
    /* this.$store.commit('setLoginStatus', true) // to Change value in store
    console.log(this.$store.state.LoginStatusStore.username) // get value from store */
    if (this.valid) {
      this.loading = true;
      const data = encrypt(JSON.stringify({username: this.username, password: this.password}));
      Axios.post(new b64('L2FkbWluL2xvZ2lu').decode(), {data})
        .then((res: AxiosResponse) => {
          const result = res.data
          switch (result.code as string) {
            case 'login00':
              localStorage.setItem('token', result.comment)
              this.$store.commit('setLoginStatus', true)
              this.$store.commit('setUsername', this.username);
              this.snackbar = true;
              this.snackbarMessage = l('layout.login.success') + ' ' + this.username;
              this.toprightdialog = false;
              break;
            default:
              this.snackbar = true;
              this.snackbarMessage = result.comment;
              break;
          }
          this.loading = false;
        })
    }
  }
}
</script>

// src/public/scripts/materialui/LoginDialog.tsx
import Dialog from '@material-ui/core/Dialog';
import React from 'react';
import {CircularProgress, createStyles, DialogTitle, TextField, Theme} from '@material-ui/core';
import DialogContent from '@material-ui/core/DialogContent';
import DialogActions from '@material-ui/core/DialogActions';
import {LoginDialogProp} from './interfaces';
import DialogContentText from '@material-ui/core/DialogContentText';
import Button from '@material-ui/core/Button';
import Snackbar from '@material-ui/core/Snackbar';
import {AJAX, AjaxResult} from '../ajax';
import {b64} from '../b64';
import IconButton from '@material-ui/core/IconButton';
import CloseIcon from '@material-ui/icons/Close';
import {l} from '../locale';
import Backdrop from '@material-ui/core/Backdrop';
import {Register} from '../register';
import RegisterDialog from './RegisterDialog';
import Axios, {AxiosError, AxiosResponse} from 'axios';
import {LoginResponse} from '../repsonseBody';
import {Simulate} from 'react-dom/test-utils';
import encrypted = Simulate.encrypted;
import {encrypt} from '../encryption/AES';

enum MessageType {
    ERROR, SUCCESS, STANDBY
}

interface LoginDialogState {
    username: string;
    usernameInvalid: boolean;
    password: string;
    passwordInvalid: boolean;
    messageType: MessageType;
    message: string;
    snackbarOpen: boolean;
    process: boolean;
    registerDialog: boolean;
}

class LoginDialog extends React.Component<LoginDialogProp, LoginDialogState> {
    constructor(props: LoginDialogProp) {
        super(props);
        this.state = {
            username: '',
            usernameInvalid: true,
            password: '',
            passwordInvalid: true,
            messageType: MessageType.STANDBY,
            message: '',
            snackbarOpen: false,
            process: false,
            registerDialog: false
        }
    }

    handleLogin = (): void => {
        if (this.state.usernameInvalid || this.state.passwordInvalid) {
            this.setState({
                messageType: MessageType.ERROR,
                message: l('layout.login.invalidinput'),
                snackbarOpen: true,
            });
            return;
        }
        this.setState({process: true});
        const data = encrypt(JSON.stringify({username: this.state.username, password: this.state.password}));
        Axios.post(new b64('L2FkbWluL2xvZ2lu').decode(), {data})
            .then((r: AxiosResponse<LoginResponse>) => {
                if (r.data.code === 'login00') {
                    localStorage.setItem('token', r.data.comment)
                    // this.props.setLoginStatus(true, result.comment)
                    location.reload()
                } else {
                    throw new Error(r.data.comment);
                }
            })
            .catch((e: Error) => {
                this.setState({
                    messageType: MessageType.ERROR,
                    message: e.message,
                    snackbarOpen: true,
                    process: false
                });
            })
    }

    handleFieldChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
        const value = e.currentTarget.value;
        switch (e.currentTarget.id) {
            case 'username':
                this.setState({username: value, usernameInvalid: !Register.validateUsername(value)})
                break;
            case 'password':
                this.setState({password: value, passwordInvalid: !Register.validatePassword(value)})
                break;
        }
    }

    handleSnackbarClose = (): void => {
        this.setState({snackbarOpen: false});
    }

    getSnackbar = (type: MessageType, message: string): JSX.Element => {
        let severity = 'success'
        const closeButton: JSX.Element = (
            <IconButton aria-label="close" color="secondary" onClick={this.handleSnackbarClose}>
                <CloseIcon/>
            </IconButton>
        )
        switch (type) {
            case MessageType.ERROR:
                severity = 'error'
            case MessageType.SUCCESS:
                /* <MuiAlert elevation={6} variant={'filled'} severity={severity}> */
                return <Snackbar open={this.state.snackbarOpen} autoHideDuration={4000}
                                 onClose={this.handleSnackbarClose} message={message} action={closeButton}/>
            case MessageType.STANDBY:
            default:
                return <></>
        }
    }

    handleRegister = (): void => {
        this.setState({registerDialog: true});
    }

    closeRegister = (): void => {
        this.setState({registerDialog: false});
    }

    handleEnterKey = (e: React.KeyboardEvent<Element>): void => {
        if (e.keyCode === 13) {
            this.handleLogin();
        }
    }

    render(): React.ReactElement {
        return (
            <>
                <Dialog open={this.props.open} onClose={this.props.handleClose}>
                    <DialogTitle>{l('layout.login.title')}</DialogTitle>
                    <DialogContent>
                        <DialogContentText>
                            {l('layout.login.description')}
                        </DialogContentText>
                        <TextField margin={'dense'} id={'username'} label={l('layout.login.username')}
                                   type={'text'} fullWidth onChange={this.handleFieldChange} error={this.state.usernameInvalid}/>
                        <TextField margin={'normal'} id={'password'} label={l('layout.login.password')}
                                   type={'password'} fullWidth onChange={this.handleFieldChange} error={this.state.passwordInvalid} onKeyDown={this.handleEnterKey}/>
                        <DialogActions>
                            <Button onClick={this.props.handleClose} color={'inherit'}>
                                {l('layout.login.close')}
                            </Button>
                            <Button onClick={this.handleRegister} color={'inherit'}>
                                {l('layout.login.register')}
                            </Button>
                            <Button onClick={this.handleLogin} color={'primary'}>
                                {l('layout.login.login')}
                            </Button>
                        </DialogActions>
                    </DialogContent>
                </Dialog>
                <Backdrop open={this.state.process} style={{zIndex: 999999}}>
                    <CircularProgress color={'inherit'}/>
                </Backdrop>
                {this.getSnackbar(this.state.messageType, this.state.message)}
                <RegisterDialog open={this.state.registerDialog} handleClose={this.closeRegister} />
            </>
        )
    }
}


export default LoginDialog;
